name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: qinvideo/qinvideo-docs:latest
      - 
        name: curl
        uses: wei/curl@v1
        with:
          args: --insecure -u ${{secrets.RANCHER_TOKEN}} -X POST -H 'Content-Type:application/json' ${{secrets.RANCHER_API}}/v3/project/c-jk8df:p-zkthp/workloads/deployment:default:qinvideo-docs?action=redeploy
